### ISSUE TITLE
[ Istio JWT] Cannot create a working API rule for a function workload

### ISSUE THREAD

**Issue by ptesny** [kyma-project/api-gateway#321] opened 2023-04-18 14:26 UTC
Description
API Rule with Istio JWT handler fails validation with a function workload; It looks like the injection checker logic error;

Steps to reproduce

Create a function in a namespace where istio side car has been enabled for the namespace
Create an API rule with Istio JWT for the function's service
API Rule has status Error

Expected result
API Rule validation ends in success

Actual result
API Rule has status Error
API Rule created with Istio JWT for a function workload will try to pick the function job's pod instead of the function's pod

**Comment by ptesny** [comment] 2023-04-19 09:42
Similar to https://github.com/kyma-project/api-gateway/issues/278 ?

**Comment by strekm** [comment] 2023-04-19 12:20
do not introduce dependency to function implementing integration test to cover that fix

**Comment by ptesny** [comment] 2023-05-04 08:51
what is your API rule yaml ?

**Comment by barchw** [comment] 2023-05-04 11:23
@ptesny OK, now I understand the problem. It is indeed caused by https://github.com/kyma-project/api-gateway/issues/278, as the function deployment doesn't have the `app: toto` label by default, so the Authorization Policy is not applied to the pod sidecar. I misunderstood first that the ApiRule gets into `Error` status.
We will fix this issue in this sprint, so I will mention you when it is ready, so you can check whether your problem is resolved.

**Comment by ptesny** [comment] 2023-05-04 11:40
Does it mean your smoke testing excludes serverless? Please kindly notice the initial misbehaviour reported is real. The error was coming from the fact the function’s job pod was being picked to create istio authorization objectsI hope that clarifies and helpsSent from my iPhoneOn 4 May 2023, at 12:23, Bartosz Chwila ***@***.***> wrote:﻿
@ptesny OK, now I understand the problem. It is indeed caused by #278, as the function deployment doesn't have the app: toto label by default, so the Authorization Policy is not applied to the pod sidecar. I misunderstood first that the ApiRule gets into Error status.
We will fix this issue in this sprint, so I will mention you when it is ready, so you can check whether your problem is resolved.

**Comment by barchw** [comment] 2023-05-04 11:45
Correct, our current smoke tests are not using serverless (at this moment). We will provide a test setup to check for this use case.
Currently we are not taking into account any Pod present on the cluster and the API Gateway controller is blindly assuming that the target pod will have the `app: toto` label.

**Comment by barchw** [comment] 2023-05-09 06:23
Hello @ptesny the [fix](https://github.com/kyma-project/api-gateway/pull/338) was merged into Kyma: https://github.com/kyma-project/kyma/pull/17452 and will be part of Kyma 2.14

**Comment by kwiatekus** [comment] 2023-05-15 09:26
Hi @strekm @barchw  what is the contract for serverless controller to make sure that function is exposable?

**Comment by ptesny** [comment] 2023-05-15 09:50
> Hello @ptesny the [fix](https://github.com/kyma-project/api-gateway/pull/338) was merged into Kyma: [kyma-project/kyma#17452](https://github.com/kyma-project/kyma/pull/17452) and will be part of Kyma 2.14

The basic smoke test seems to be working now: getting `RBAC: access denied` message;  
still this only a partial test; a complete test would include calling the API rule with the JWT token in the `Authorization` header;


I checked the error code is 403 (**forbidden**). With ory it would have been 401 (**unauthorized**)?
Why the behaviour of ory based versus istio base API rule with JWT access strategy differs ? Having unauthorized (401) which means no access versus forbidden (403) which means no permissions error code is not the same?

IMO calling a API rule without a JWT token or with an expired one should return 401 ?

**Comment by barchw** [comment] 2023-05-16 08:00
The response of `403` is present because the validation of the request is failing on Authorization Policy that is prohibiting calls without a valid JWT token. We discussed today that this is a breaking change that we will document for the customers.

**Comment by ptesny** [comment] 2023-05-19 08:02
@barchw , is there a pointer to istio documentation that describes this behaviour ?

**Comment by barchw** [comment] 2023-05-19 08:08
Please have a look at this comment: https://github.com/istio/istio/issues/26559#issuecomment-675682440

**Comment by ptesny** [comment] 2023-05-19 08:59
Thanks for the pointer; but it looks to me is nonetheless a very, very opinionated behaviour of istio. 

I'd rather expect that kyma api gateway CRD would rather act as a go-between insulating end users from opinionated behaviour of open source components ;

**Comment by barchw** [comment] 2023-05-24 12:36
Closing the issue as the original problem was resolved in https://github.com/kyma-project/api-gateway/pull/338

**Closed by barchw** 2023-05-24 12:36 UTC
Labels: kind/bug
