### ISSUE TITLE
Error when "corsPolicy" spec is added

### ISSUE THREAD

**Issue by tonymathew17sap** [kyma-project/api-gateway#814] opened 2024-01-17 14:20 UTC
**Description**
As per Kyma documentation [here](https://kyma-project.io/#/api-gateway/user/custom-resources/apirule/04-10-apirule-custom-resource:~:text=the%20Istio%20Gateway.-,corsPolicy,-NO), corsPolicy is supported. However, I'm getting the following error:
`strict decoding error: unknown field "spec.corsPolicy"`

**Expected result**
'corsPolicy' spec should be supported

**Actual result**
Getting the error: 
`strict decoding error: unknown field "spec.corsPolicy"`

**Steps to reproduce**
1. Use the following K8s file:
```
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  labels:
    app: approuter
  name: approuter
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: vehicle-service-approuter.c7faf5c.kyma.ondemand.com
  corsPolicy:
    allowCredentials: 'true'
  rules:
    - path: /.*
      methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
      service:
        name: approuter
        port: 5000
      accessStrategies:
        - handler: noop
```
Getting the error:
`strict decoding error: unknown field "spec.corsPolicy"`

**Troubleshooting**

**Comment by barchw** [comment] 2024-05-07 13:10
Hey @tonymathew17sap, I cannot reproduce the issue. Is the issue still relevant on your side? If so, what is the api-gateway module version you are using?

**Comment by barchw** [comment] 2024-05-10 10:18
I will close the issue for now, @tonymathew17sap if you happen to come across it again, please re-open

**Closed by barchw** 2024-05-10 10:18 UTC
Labels: kind/bug
